apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: europe-west1-docker.pkg.dev/tjts5901-452510/flask-repo/flask-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: flask-env
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/secrets/key.json"
          volumeMounts:
            - name: gcp-secret-volume
              mountPath: "/secrets"
              readOnly: true
      volumes:
        - name: gcp-secret-volume
          secret:
            secretName: gcp-sa-key

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-env
data:
  OPEN_W_API_KEY: "dummy-placeholder"
  SECRET_KEY: "dummy-placeholder"
  WEATHER_API_KEY: "dummy-placeholder"

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
