name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      
      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin
          gcloud components update
      
      - name: Configure Docker Authentication
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev
          
      - name: Get GKE Credentials  
        run: gcloud container clusters get-credentials flask-cluster --region europe-west1

      - name: Build and Push Docker Image
        run: |
          docker build -t europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/flask-repo/flask-app:latest .
          docker push europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/flask-repo/flask-app:latest

      - name: Create Kubernetes Secret for GCP Key
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > key.json  
          kubectl create secret generic gcp-sa-key --from-file=key.json --dry-run=client -o yaml | kubectl apply -f -
          rm key.json

        
      - name: Create ConfigMap for API Keys
        run: |
          kubectl delete configmap flask-env --ignore-not-found
          kubectl create configmap flask-env \
            --from-literal=OPEN_W_API_KEY="${{ secrets.OPEN_W_API_KEY }}" \
            --from-literal=SECRET_KEY="${{ secrets.SECRET_KEY }}" \
            --from-literal=WEATHER_API_KEY="${{ secrets.WEATHER_API_KEY }}"


      - name: Deploy to GKE
        run: kubectl apply -f deployment.yaml

      - name: Restart Deployment
        run: kubectl rollout restart deployment flask-app